<?php
	if (!isset($_SESSION)) session_start();
    error_reporting(0);
    //split the url generated by htaccess
	$self_url = $_GET['x'];
	$self_url_split = explode("/",$self_url);
	if ($self_url_split[0]){ $arg_one = strtolower($self_url_split[0]); }
	if ($self_url_split[1]){ $arg_two = strtolower($self_url_split[1]); }
	if ($self_url_split[2]){ $arg_three = strtolower($self_url_split[2]); }
	  
	//load appropriate file based on url length
	if ($arg_one=='') {
		include_once("home.php");
	} else if (($arg_one=='login') && (!$arg_two)){
        include_once("login.php");
    } else if (($arg_one=='register') && (!$arg_two)){
        include_once("register.php");
    } else if (($arg_one=='change-password') && (!$arg_two)){
        include_once("changepass.php");
    } else if (($arg_one=='chats')){
        include_once("chats.php");
    } else if (($arg_one=='subscriptions')){
        include_once("subscriptions.php");
    } else if (($arg_one=='forgotpass') && (!$arg_two)){
        include_once("forgotpass.php");
    } else if ($arg_one=='error'){
        include_once("error_page.php");
    } 
	 
?>